# Generated by Django 6.0.3 on 2026-04-03 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('link_video', models.URLField(blank=True)),
                ('musculo_trabalhado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GymControl.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='TreinoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_series', models.IntegerField()),
                ('qtd_repeticoes', models.IntegerField()),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GymControl.exercicio')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GymControl.treino')),
            ],
        ),
    ]
