# Generated by Django 6.0.3 on 2026-04-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymControl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='musculo_trabalhado',
            field=models.CharField(choices=[('abdomen', 'Abdômen'), ('aerobico', 'Aeróbico'), ('peito', 'Peito'), ('triceps', 'Tríceps'), ('biceps', 'Bíceps'), ('antebraco', 'Antebraço'), ('costas', 'Costas'), ('anterior_perna', 'Anterior de perna'), ('posterior_perna', 'Posterior de perna'), ('ombro', 'Ombro'), ('panturrilha', 'Panturrilha')], max_length=30),
        ),
    ]
