# Generated by Django 6.0.3 on 2026-04-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymControl', '0002_alter_exercicio_musculo_trabalhado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
